SCHEMA_V1 = """
CREATE TABLE IF NOT EXISTS vault_entries (
    id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, username TEXT,
    encrypted_password TEXT, url TEXT, notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, tags TEXT
);
CREATE TABLE IF NOT EXISTS audit_log (id INTEGER PRIMARY KEY AUTOINCREMENT, action TEXT NOT NULL, timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP, entry_id INTEGER, details TEXT, signature TEXT);
CREATE TABLE IF NOT EXISTS settings (id INTEGER PRIMARY KEY AUTOINCREMENT, setting_key TEXT UNIQUE NOT NULL, setting_value TEXT, encrypted INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS key_store (id INTEGER PRIMARY KEY AUTOINCREMENT, key_type TEXT, salt BLOB, hash BLOB, params TEXT);
CREATE INDEX IF NOT EXISTS idx_vault_title ON vault_entries(title);
CREATE INDEX IF NOT EXISTS idx_audit_timestamp ON audit_log(timestamp);
"""

SCHEMA_V3_UPDATE = """
CREATE TABLE IF NOT EXISTS key_store_new (
    id INTEGER PRIMARY KEY AUTOINCREMENT, key_type TEXT NOT NULL, key_data BLOB,
    version INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
DROP TABLE IF EXISTS key_store;
ALTER TABLE key_store_new RENAME TO key_store;
"""
